accent        : "F58A07"
headline      : "Architecting AI • Turning ideas into impact"
emoji_role    : "🧠"
about_me      : |
  I'm a Machine Learning Engineer specializing in building intelligent, scalable systems that translate complex data into tangible business impact. With a deep focus on Natural Language Processing (NLP) and Large Language Models (LLMs), I thrive on architecting solutions that bridge the gap between cutting-edge research and real-world application.

  My current work involves developing advanced Graph-RAG systems to enhance information retrieval and building multimodal AI assistants for complex triage scenarios. I'm passionate about open-source and believe that constraints breed creativity.
current_projects:
  - "Graph-RAG Toolkit 🔗"
  - "Care.ai v2 – multimodal triage assistant 🚑"
badges:
  - python
  - pytorch
  - kubernetes
metrics:
  prs_merged      : true
  issues_closed   : true
  top_languages   : 5
blog_rss         : "https://sraj.ai/rss.xml"
socials:
  linkedin: siddharth-rajagopalan
  twitter: _SiddharthR
  email: siddharth.rajagopalan01@gmail.com
  